# Generated by Django 5.1.4 on 2024-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestial',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
